include: "rules/common.smk"

##### Target rules #####

rule all:
    input:
        "data/output/qc/multiqc.html",
        "data/output/called/merged.vcf.gz",
        # expand("data/output/deepvariant/gvcf/{sample}.gvcf.gz",
        #     sample = samples.index)

##### Modules #####
include: "rules/mapping.smk"
include: "rules/calling.smk"
